# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
        language_version: python3.11
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Black formatter - uses config from pyproject.toml
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        args: ['--config=pyproject.toml']

  # Ruff linter - uses config from pyproject.toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: ['--config=pyproject.toml', '--fix']

  # MyPy type checker - uses config from pyproject.toml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        language_version: python3.11
        args: ['--config-file=pyproject.toml']
        additional_dependencies:
          - numpy>=1.24
          - hypothesis>=6.0
        files: ^src/
        pass_filenames: true

# Configuration
default_language_version:
  python: python3.11

exclude: '^(\.git|\.venv|venv|build|dist|\.eggs|.*\.egg-info)/'

fail_fast: false